/**
 * Drizzle schema — Backend v2.
 *
 * Source of truth: `specs/001-backend-v2/data-model.md`.
 * Eleven tables; all primary keys are 26-char ULIDs (generated by `lib/ids.ts`,
 * landing in T012) except `audit_log.id` (auto-increment integer for monotonic
 * ordering and signature chain).
 *
 * Timestamps are stored as INTEGER epoch milliseconds. We do NOT use Drizzle's
 * `{ mode: 'timestamp_ms' }` type-modifier here because:
 *   1. We want the DB schema to be plain SQLite INTEGER NOT NULL (no implicit
 *      type-checking magic that diverges from raw SQL clients).
 *   2. The audit-log canonical message format requires manual ISO 8601
 *      formatting of `ts` anyway, so a `Date` round-trip would only complicate
 *      the canonicalization code.
 *
 * Status / severity / outcome enums are NOT enforced via CHECK constraints at
 * the DB layer. SQLite supports CHECK, and drizzle-orm 0.36 exposes `check()`,
 * but per the constitution we validate at system boundaries with Zod (see
 * `lib/validation.ts`, T012). Pushing string-enum invariants into the DB would
 * fragment validation across two layers and break the "fail-fast with clear
 * error messages" principle. Surprise documented in commit message.
 */

import { sql } from "drizzle-orm";
import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// ---------------------------------------------------------------------------
// users
// ---------------------------------------------------------------------------
export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => ({
    emailUq: uniqueIndex("users_email_uq").on(t.email),
  }),
);

// ---------------------------------------------------------------------------
// sessions
// ---------------------------------------------------------------------------
export const sessions = sqliteTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: integer("created_at").notNull(),
    expiresAt: integer("expires_at").notNull(),
  },
  (t) => ({
    userIdx: index("sessions_user_id_idx").on(t.userId),
    expiresIdx: index("sessions_expires_at_idx").on(t.expiresAt),
  }),
);

// ---------------------------------------------------------------------------
// magic_link_tokens — no FK to users (email may belong to a not-yet-existing user)
// ---------------------------------------------------------------------------
export const magicLinkTokens = sqliteTable(
  "magic_link_tokens",
  {
    token: text("token").primaryKey(),
    email: text("email").notNull(),
    expiresAt: integer("expires_at").notNull(),
    usedAt: integer("used_at"),
  },
  (t) => ({
    emailIdx: index("magic_link_tokens_email_idx").on(t.email),
    expiresIdx: index("magic_link_tokens_expires_at_idx").on(t.expiresAt),
  }),
);

// ---------------------------------------------------------------------------
// projects
// ---------------------------------------------------------------------------
export const projects = sqliteTable(
  "projects",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => ({
    userIdx: index("projects_user_id_idx").on(t.userId),
  }),
);

// ---------------------------------------------------------------------------
// targets
// ---------------------------------------------------------------------------
export const targets = sqliteTable(
  "targets",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    status: text("status").$type<"unverified" | "verified" | "expired">().notNull(),
    verifiedAt: integer("verified_at"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => ({
    projectIdx: index("targets_project_id_idx").on(t.projectId),
    statusIdx: index("targets_status_idx").on(t.status),
  }),
);

// ---------------------------------------------------------------------------
// auth_proofs
// ---------------------------------------------------------------------------
export const authProofs = sqliteTable(
  "auth_proofs",
  {
    id: text("id").primaryKey(),
    targetId: text("target_id")
      .notNull()
      .references(() => targets.id, { onDelete: "cascade" }),
    challenge: text("challenge").notNull(),
    method: text("method").$type<"dns_txt" | "file" | "meta_tag" | null>(),
    status: text("status").$type<"pending" | "verified" | "expired">().notNull(),
    createdAt: integer("created_at").notNull(),
    verifiedAt: integer("verified_at"),
    expiresAt: integer("expires_at").notNull(),
  },
  (t) => ({
    targetIdx: index("auth_proofs_target_id_idx").on(t.targetId),
    statusIdx: index("auth_proofs_status_idx").on(t.status),
    expiresIdx: index("auth_proofs_expires_at_idx").on(t.expiresAt),
  }),
);

// ---------------------------------------------------------------------------
// scans
// ---------------------------------------------------------------------------
export const scans = sqliteTable(
  "scans",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    targetId: text("target_id")
      .notNull()
      .references(() => targets.id, { onDelete: "cascade" }),
    profile: text("profile").$type<"recon" | "standard" | "max">().notNull(),
    status: text("status")
      .$type<"queued" | "running" | "completed" | "failed" | "cancelled">()
      .notNull(),
    failureReason: text("failure_reason"),
    startedAt: integer("started_at").notNull(),
    completedAt: integer("completed_at"),
    usageTokens: integer("usage_tokens"),
    usageUsdCents: integer("usage_usd_cents"),
  },
  (t) => ({
    userIdx: index("scans_user_id_idx").on(t.userId),
    targetIdx: index("scans_target_id_idx").on(t.targetId),
    statusIdx: index("scans_status_idx").on(t.status),
  }),
);

// ---------------------------------------------------------------------------
// findings
// ---------------------------------------------------------------------------
export const findings = sqliteTable(
  "findings",
  {
    id: text("id").primaryKey(),
    scanId: text("scan_id")
      .notNull()
      .references(() => scans.id, { onDelete: "cascade" }),
    severity: text("severity")
      .$type<"critical" | "high" | "medium" | "low" | "info">()
      .notNull(),
    title: text("title").notNull(),
    bodyMd: text("body_md").notNull(),
    evidenceJson: text("evidence_json"),
    createdAt: integer("created_at").notNull(),
    dedupKey: text("dedup_key").notNull(),
  },
  (t) => ({
    scanIdx: index("findings_scan_id_idx").on(t.scanId),
    dedupUq: uniqueIndex("findings_dedup_key_uq").on(t.dedupKey),
  }),
);

// ---------------------------------------------------------------------------
// audit_log — INTEGER PK AUTOINCREMENT for monotonic ordering; no FKs
// (data-model.md keeps these as nullable string references for operational
// flexibility — audit rows must never be blocked by referential integrity).
// ---------------------------------------------------------------------------
export const auditLog = sqliteTable(
  "audit_log",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ts: integer("ts").notNull(),
    event: text("event").notNull(),
    userId: text("user_id"),
    projectId: text("project_id"),
    targetId: text("target_id"),
    scanId: text("scan_id"),
    vpsInstanceId: text("vps_instance_id"),
    authProofId: text("auth_proof_id"),
    findingId: text("finding_id"),
    severity: text("severity"),
    outcome: text("outcome").$type<"success" | "failure" | "rejected">().notNull(),
    metadataJson: text("metadata_json").notNull(),
    prevSignature: text("prev_signature").notNull(),
    signature: text("signature").notNull(),
  },
  (t) => ({
    scanIdx: index("audit_log_scan_id_idx").on(t.scanId),
    eventIdx: index("audit_log_event_idx").on(t.event),
    tsIdx: index("audit_log_ts_idx").on(t.ts),
  }),
);

// ---------------------------------------------------------------------------
// vps_instances — 1:1 with scans (scan_id UNIQUE)
// ---------------------------------------------------------------------------
export const vpsInstances = sqliteTable(
  "vps_instances",
  {
    id: text("id").primaryKey(),
    scanId: text("scan_id")
      .notNull()
      .references(() => scans.id, { onDelete: "cascade" }),
    provider: text("provider").$type<"hetzner">().notNull(),
    providerServerId: text("provider_server_id").notNull(),
    ipv4: text("ipv4"),
    status: text("status")
      .$type<"provisioning" | "alive" | "tearing_down" | "destroyed">()
      .notNull(),
    signKey: text("sign_key").notNull(),
    createdAt: integer("created_at").notNull(),
    destroyedAt: integer("destroyed_at"),
  },
  (t) => ({
    scanUq: uniqueIndex("vps_instances_scan_id_uq").on(t.scanId),
    statusIdx: index("vps_instances_status_idx").on(t.status),
  }),
);

// ---------------------------------------------------------------------------
// jobs — composite (status, scheduled_at) is the worker's hot path
// ---------------------------------------------------------------------------
export const jobs = sqliteTable(
  "jobs",
  {
    id: text("id").primaryKey(),
    type: text("type")
      .$type<"spawn_vps" | "dispatch_scan" | "watchdog_scan" | "teardown_vps">()
      .notNull(),
    payloadJson: text("payload_json").notNull(),
    status: text("status")
      .$type<"pending" | "running" | "done" | "failed">()
      .notNull(),
    scheduledAt: integer("scheduled_at").notNull(),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => ({
    statusScheduledIdx: index("jobs_status_scheduled_at_idx").on(
      t.status,
      t.scheduledAt,
    ),
    typeIdx: index("jobs_type_idx").on(t.type),
  }),
);

// ---------------------------------------------------------------------------
// Inferred row types — consumed by repositories in later tasks.
// ---------------------------------------------------------------------------
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
export type MagicLinkToken = typeof magicLinkTokens.$inferSelect;
export type NewMagicLinkToken = typeof magicLinkTokens.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type NewProject = typeof projects.$inferInsert;
export type Target = typeof targets.$inferSelect;
export type NewTarget = typeof targets.$inferInsert;
export type AuthProof = typeof authProofs.$inferSelect;
export type NewAuthProof = typeof authProofs.$inferInsert;
export type Scan = typeof scans.$inferSelect;
export type NewScan = typeof scans.$inferInsert;
export type Finding = typeof findings.$inferSelect;
export type NewFinding = typeof findings.$inferInsert;
export type AuditLog = typeof auditLog.$inferSelect;
export type NewAuditLog = typeof auditLog.$inferInsert;
export type VpsInstance = typeof vpsInstances.$inferSelect;
export type NewVpsInstance = typeof vpsInstances.$inferInsert;
export type Job = typeof jobs.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;

// Suppress unused-import warning for `sql` (kept available for future
// custom defaults like `sql\`unixepoch() * 1000\``).
void sql;
