import { describe, it, expect } from "bun:test";
import { canonicalMessage, signEntry, type AuditEntry } from "./sign.ts";

// ---------------------------------------------------------------------------
// Reference vectors generated by an independent Node script (see commit msg).
// Bit-for-bit stability is the load-bearing invariant — Constitution II says
// the verify-chain must keep working on historical hashes. Do NOT update
// these without a coordinated chain-versioning migration.
// ---------------------------------------------------------------------------

const KEY = "test-key";

const baseEntry: AuditEntry = {
  event: "scan_started",
  ts: 1700000000000, // epoch ms → "2023-11-14T22:13:20.000Z"
  userId: "u_01",
  projectId: "p_01",
  targetId: "t_01",
  scanId: "s_01",
  vpsInstanceId: null,
  authProofId: null,
  findingId: null,
  severity: null,
  outcome: "success",
  metadataJson: {},
};

describe("canonicalMessage", () => {
  it("produces 13 pipe-delimited fields for a minimal entry with empty metadata and no prev_sig", () => {
    const m = canonicalMessage(baseEntry, "");
    expect(m).toBe(
      "scan_started|2023-11-14T22:13:20.000Z|u_01|p_01|t_01|s_01|||||success|{}|",
    );
    // 13 pipe-separated fields ⇒ exactly 12 `|` characters.
    expect((m.match(/\|/g) ?? []).length).toBe(12);
  });

  it("alpha-sorts top-level metadata keys for stable JSON encoding", () => {
    const entry: AuditEntry = {
      ...baseEntry,
      event: "decepticon_invoked",
      ts: 1700000060000,
      projectId: null,
      targetId: null,
      metadataJson: { b: 1, a: 2 },
    };
    const m = canonicalMessage(entry, "");
    expect(m).toBe(
      'decepticon_invoked|2023-11-14T22:14:20.000Z|u_01|||s_01|||||success|{"a":2,"b":1}|',
    );
    // Verify alpha-sort: `"a"` appears before `"b"` in the JSON segment.
    const json = m.split("|")[11];
    expect(json).toBe('{"a":2,"b":1}');
  });

  it("renders empty metadata as `{}`", () => {
    const m = canonicalMessage({ ...baseEntry, metadataJson: {} }, "");
    expect(m).toContain("|{}|");
  });

  it("alpha-sort applies to top-level keys only — nested values pass through as-is", () => {
    // Decision: match EE-2 behaviour (top-level sort only). Recursive sort
    // was considered and rejected to keep the implementation trivial — if a
    // caller wants stable nested ordering, they must canonicalise before
    // passing the metadata.
    const m = canonicalMessage(
      { ...baseEntry, metadataJson: { b: { z: 1, a: 2 }, a: 1 } },
      "",
    );
    expect(m).toBe(
      'scan_started|2023-11-14T22:13:20.000Z|u_01|p_01|t_01|s_01|||||success|{"a":1,"b":{"z":1,"a":2}}|',
    );
  });

  it("renders nullable string columns as empty fields", () => {
    const m = canonicalMessage(baseEntry, "");
    // Fields 7..10 (vpsInstanceId, authProofId, findingId, severity) all null.
    const parts = m.split("|");
    expect(parts[6]).toBe(""); // vpsInstanceId
    expect(parts[7]).toBe(""); // authProofId
    expect(parts[8]).toBe(""); // findingId
    expect(parts[9]).toBe(""); // severity
  });

  it("includes prev_signature as the 13th field", () => {
    const prev = "deadbeef".repeat(8);
    const m = canonicalMessage(baseEntry, prev);
    expect(m.endsWith(`|${prev}`)).toBe(true);
    const parts = m.split("|");
    expect(parts.length).toBe(13);
    expect(parts[12]).toBe(prev);
  });

  it("renders ts (epoch ms) as ISO 8601 UTC", () => {
    const m = canonicalMessage({ ...baseEntry, ts: 0 }, "");
    expect(m.split("|")[1]).toBe("1970-01-01T00:00:00.000Z");
  });

  it("renders a populated entry with severity and finding_id", () => {
    const entry: AuditEntry = {
      event: "finding_recorded",
      ts: 1700000120000,
      userId: null,
      projectId: "p_01",
      targetId: "t_01",
      scanId: "s_01",
      vpsInstanceId: "v_01",
      authProofId: null,
      findingId: "f_01",
      severity: "high",
      outcome: "success",
      metadataJson: { cve: "CVE-2024-1234" },
    };
    const m = canonicalMessage(entry, "");
    expect(m).toBe(
      'finding_recorded|2023-11-14T22:15:20.000Z||p_01|t_01|s_01|v_01||f_01|high|success|{"cve":"CVE-2024-1234"}|',
    );
  });
});

describe("signEntry", () => {
  it("returns deterministic hex HMAC-SHA256 (vector 1: empty metadata, no prev_sig)", () => {
    const sig = signEntry(KEY, baseEntry, null);
    expect(sig).toBe(
      "3cb4ea33c262dc95c87512223e48213fc58b08e086d2f55f3c470f8112717fa4",
    );
    expect(sig).toMatch(/^[0-9a-f]{64}$/);
  });

  it("returns deterministic hex HMAC-SHA256 (vector 2: alpha-sort metadata)", () => {
    const entry: AuditEntry = {
      ...baseEntry,
      event: "decepticon_invoked",
      ts: 1700000060000,
      projectId: null,
      targetId: null,
      metadataJson: { b: 1, a: 2 },
    };
    const sig = signEntry(KEY, entry, null);
    expect(sig).toBe(
      "b4dfc9e7bb59f163130f1042f46d70e62697958ab3792ad974788d8dee3dc9aa",
    );
  });

  it("chains: same entry body produces different sig when prev_sig changes (vector 3)", () => {
    const sig1 = signEntry(KEY, baseEntry, null);
    const sig2 = signEntry(KEY, baseEntry, sig1);
    expect(sig2).toBe(
      "8914a6d00ac13fff70d45fd36227bab51fdca639c0927168a79c167c290edb93",
    );
    expect(sig2).not.toBe(sig1);
  });

  it("treats null prev_sig identically to empty string (first row of chain)", () => {
    const a = signEntry(KEY, baseEntry, null);
    const b = signEntry(KEY, baseEntry, "");
    expect(a).toBe(b);
  });

  it("nested metadata: top-level sort, nested unchanged (vector 4)", () => {
    const sig = signEntry(
      KEY,
      { ...baseEntry, metadataJson: { b: { z: 1, a: 2 }, a: 1 } },
      null,
    );
    expect(sig).toBe(
      "bb2076fc830ee56dbab8a9c3cf27d2755629f9b2aaf11256284255412df2cc53",
    );
  });

  it("populated entry with severity (vector 5)", () => {
    const entry: AuditEntry = {
      event: "finding_recorded",
      ts: 1700000120000,
      userId: null,
      projectId: "p_01",
      targetId: "t_01",
      scanId: "s_01",
      vpsInstanceId: "v_01",
      authProofId: null,
      findingId: "f_01",
      severity: "high",
      outcome: "success",
      metadataJson: { cve: "CVE-2024-1234" },
    };
    expect(signEntry(KEY, entry, null)).toBe(
      "efd01fc3d7e078719f7b18db420376b76c269494b3cf166c48984723f1664fe5",
    );
  });

  it("same input → same output bit-for-bit", () => {
    const a = signEntry(KEY, baseEntry, null);
    const b = signEntry(KEY, baseEntry, null);
    expect(a).toBe(b);
  });

  it("different key → different signature", () => {
    const a = signEntry("key-1", baseEntry, null);
    const b = signEntry("key-2", baseEntry, null);
    expect(a).not.toBe(b);
  });

  it("tampering with metadata invalidates the signature", () => {
    const original = signEntry(KEY, baseEntry, null);
    const tampered = signEntry(
      KEY,
      { ...baseEntry, metadataJson: { evil: 1 } },
      null,
    );
    expect(original).not.toBe(tampered);
  });
});
