import type { ReportSnapshot } from './models.ts';

const esc = (s: unknown): string =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const severityBadge = (s: string): string => {
  const colors: Record<string, string> = {
    critical: '#d32f2f',
    high: '#e64a19',
    medium: '#f57c00',
    low: '#388e3c',
    info: '#1976d2',
  };
  const color = colors[s.toLowerCase()] ?? '#757575';
  return `<span style="background:${color};color:#fff;padding:2px 8px;border-radius:3px;font-size:12px;font-weight:bold">${esc(s.toUpperCase())}</span>`;
};

const renderFinding = (f: ReportSnapshot['findings'][number], idx: number): string => `
  <section class="finding" id="finding-${esc(f.id)}">
    <h3>${idx + 1}. ${esc(f.type)} ${severityBadge(f.severity)}</h3>
    <table class="meta">
      <tr><th>Affected URL</th><td><code>${esc(f.affectedUrl)}</code></td></tr>
      <tr><th>Severity</th><td>${esc(f.severity)}</td></tr>
      <tr><th>Confidence</th><td>${esc(f.confidence)}</td></tr>
      <tr><th>Validated At</th><td>${esc(f.validatedAt)}</td></tr>
    </table>
    <h4>Evidence (${f.evidence.length} artifact${f.evidence.length !== 1 ? 's' : ''})</h4>
    <ul>
      ${f.evidence.map((e) => `<li>${esc(e.kind)}: sha256=${esc(e.sha256)}</li>`).join('\n      ')}
    </ul>
  </section>`;

export const renderHtml = (snapshot: ReportSnapshot): string => {
  const findingsSection =
    snapshot.findings.length === 0
      ? '<p class="no-findings">No confirmed findings for this assessment.</p>'
      : snapshot.findings.map(renderFinding).join('\n');

  const excludedNote =
    snapshot.excludedFindingCount > 0
      ? `<p class="excluded-note">Note: ${snapshot.excludedFindingCount} finding(s) excluded from this report due to scope validation.</p>`
      : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pentest Report — ${esc(snapshot.assessmentId)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 960px; margin: 40px auto; color: #212121; line-height: 1.6; }
    h1 { border-bottom: 2px solid #1976d2; padding-bottom: 8px; color: #1976d2; }
    h2 { color: #424242; margin-top: 32px; }
    h3 { color: #37474f; }
    .meta { border-collapse: collapse; width: 100%; margin: 12px 0; }
    .meta th, .meta td { padding: 8px 12px; border: 1px solid #e0e0e0; text-align: left; }
    .meta th { background: #f5f5f5; width: 160px; }
    .finding { border: 1px solid #e0e0e0; border-radius: 4px; padding: 16px; margin: 16px 0; }
    .no-findings { color: #757575; font-style: italic; }
    .excluded-note { color: #795548; background: #fff3e0; padding: 8px 12px; border-radius: 4px; }
    code { background: #f5f5f5; padding: 2px 4px; border-radius: 2px; font-size: 0.9em; }
    footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e0e0e0; color: #9e9e9e; font-size: 0.85em; }
  </style>
</head>
<body>
  <h1>Technical Pentest Report</h1>

  <section class="summary">
    <h2>Summary</h2>
    <table class="meta">
      <tr><th>Report ID</th><td>${esc(snapshot.reportId)}</td></tr>
      <tr><th>Assessment ID</th><td>${esc(snapshot.assessmentId)}</td></tr>
      <tr><th>Generated At</th><td>${esc(snapshot.generatedAt)}</td></tr>
      <tr><th>Confirmed Findings</th><td>${snapshot.findings.length}</td></tr>
      <tr><th>Excluded (OoS)</th><td>${snapshot.excludedFindingCount}</td></tr>
    </table>
  </section>

  <section class="methodology">
    <h2>Methodology</h2>
    <p>${esc(snapshot.methodology)}</p>
  </section>

  <section class="findings">
    <h2>Confirmed Findings</h2>
    ${excludedNote}
    ${findingsSection}
  </section>

  <footer>
    <p>Generated by CyberStrike report-builder. Report ID: ${esc(snapshot.reportId)}. This report is confidential.</p>
  </footer>
</body>
</html>`;
};
